---
version: "3.7"
services:
  base:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    #command: "bash"
    network_mode: "host"
    stdin_open: true
    tty: true
    privileged: true
    environment:
      ROS_MASTER_URI: "http://localhost:11311"
      GAZEBO_MASTER_URI: "http://localhost:11345"
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIE: graphics
      LIBGL_ALWAYS_INDIRECT: 0
      ROS_BU_PKG: $ROS_BU_PKG
      ROS_BU_LAUNCH: $ROS_BU_LAUNCH
      LAUNCH_ROSBRIDGE: "true"
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    devices:
      - "/dev/dri"
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
      - target: 11311
        published: 11311
        protocol: tcp
        mode: host
      - target: 11345
        published: 11345
        protocol: tcp
        mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
